### ISSUE TITLE
Unhandled 'error' event on $ gulp

### ISSUE THREAD

**Issue by datdoan** [darylldoyle/Gulp-Email-Creator#11]
node:6611) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:21:21] Using gulpfile ~/dev/Gulp-Email-Creator/gulpfile.js
[23:21:21] Starting 'sass'...
[23:21:21] Starting 'browser-sync'...
[23:21:21] Finished 'browser-sync' after 65 ms
[23:21:21] Starting 'build'...
[23:21:21] Starting 'watch'...
[23:21:21] Finished 'watch' after 17 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Unable to connect to the MailChimp API endpoint because getaddrinfo ENOTFOUND undefined.api.mailchimp.com undefined.api.mailchimp.com:443

----

Any idea?

**Comment by darylldoyle** [comment]
Yep, looks like you haven't set the `APIKEY` element in your `config.json`.

 Mailchimp is used to inline the CSS so it's a required part of the system. See [this link](http://kb.mailchimp.com/integrations/api-integrations/about-api-keys) for info on how to set up an API key in Mailchimp.

If you still run into the error, feel free to re-open this issue!
