### ISSUE TITLE
Is it possible to make online testing features easy on/off?

### ISSUE THREAD

**Issue by jitendravyas** [darylldoyle/Gulp-Email-Creator#5]
If though I have downloaded everything I'm unable to use this tool offline

Getting this error

`````````
[22:23:59] Starting 'build'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unable to connect to the MailChimp API endpoint.
````````````

**Comment by darylldoyle** [comment]
Sorry, this isn't something I'm too interested in fixing. If you can get it to work, feel free to submit a PR and I'll take a look at it.
