### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by revelt** [darylldoyle/Gulp-Email-Creator#8]
Half of all dependencies at the moment are out-of-date:
https://david-dm.org/darylldoyle/Gulp-Email-Creator#info=devDependencies&view=table

Let's set up a [GreenKeeper](https://greenkeeper.io/), it will make the dependency updating easier.

**Comment by darylldoyle** [comment]
Thanks @revelt, I've now added GreenKeeper to the repo so hopefully I'l be more on top of keeping the deps up to date!
